### ISSUE TITLE
Git Tutorial for Beginners

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#10]
Git Tutorial for Beginners: Learn Git in 1 Hour

Link: https://www.youtube.com/watch?v=8JJ101D3knE

Repository: https://gitlab.com/SyafiqHadzir/devops-notes

### Milestones

- [x] Introduction
- [x] What is Git?
- [x] Using Git
- [x] Installing Git
- [x] Configuring Git
- [x] Getting Help
- [x] Cheat Sheet
- [x] Taking Snapshots
- [x] Initializing a Repository
- [x] Git Workflow
- [x] Staging Files
- [x] Committing Changes
- [x] Committing Best Practices
- [x] Skipping the Staging Area
- [x] Removing Files
- [x] Renaming or Moving Files
- [x] Ignoring Files
- [x] Short Status
- [x] Viewing the Staged and Unstaged Changes
- [x] Visual Diff Tools
- [x] Viewing the History
- [x] Viewing a Commit
- [x] Unstaging Files
- [x] Discarding Local Changes
- [x] Restoring a File to an Earlier Version
