### ISSUE TITLE
CSS Complete Course

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#11]
Zero to Hero (Complete Course)

Link: https://www.youtube.com/watch?v=1Rs2ND1ryYc

Repository: https://gitlab.com/SyafiqHadzir/css-tutorial

### Milestones

- [ ] Course Achievements & Results
- [ ] Introduction to Course
- [ ] Downloading Necessary Software
- [ ] Where to Find Project Files
- [ ] What is CSS?
- [ ] Creating & Linking a CSS Stylesheet
- [ ] How to Test a Stylesheet
- [ ] What is a Selector?
- [ ] Classes & ID's in HTML
- [ ] Specificity & When to use Selectors
- [ ] Pseudoselectors
- [ ] Advanced Selectors
- [ ] Attribute Selectors
- [ ] What are Properties?
- [ ] The CSS General Rule
- [ ] Types of Colors
- [ ] Coloring Text
- [ ] Background Colors
- [ ] Images/URL's in CSS
- [ ] Other Background Properties
- [ ] Opacity/Transparency
- [ ] Gradients
- [ ] Introduction to Types of Units
- [ ] Text Manipulation
- [ ] Font Size, Bolding & Style
- [ ] Font Families
- [ ] Including External Fonts w/ Google Fonts
- [ ] Using External Fonts
- [ ] The CSS Box Model
- [ ] Changing Content Size
- [ ] CSS Borders
- [ ] Margin & Padding
- [ ] Float & Display Types
- [ ] What is Flexbox?
- [ ] Creating a Flex Container
- [ ] Flex Direction & Wrap
- [ ] Content Alignment
- [ ] Flex Item Order
- [ ] Shrink, Grow, & Basis
- [ ] The 'flex' Property
- [ ] Grid vs Flexbox
- [ ] Creating a Grid
- [ ] Template Columns & Rows
- [ ] Justify & Align Grid
- [ ] Row & Column Gaps
- [ ] Column & Row Lines
- [ ] Grid Area
- [ ] The Transition Property
- [ ] Transformation Functions
- [ ] Creating Animations w/ Keyframes
- [ ] Adding an Animation
- [ ] Animation Properties
- [ ] Website Transformation Challenge
- [ ] Website Transformation - SOLUTION
- [ ] What to Learn Next
