### ISSUE TITLE
Unit Testing in C# 2022

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#113]
# Unit Testing in C# 2022

Unit Testing C# Code - Tutorial for Beginners.

Link: <https://youtu.be/aq3IbO0RwAQ>

### Milestones

- [x] Intro + First Test
- [x] XUnit & Fluent Assertions
  - [x] Intro
  - [x] Network Utility
  - [x] Create Network Utility
  - [x] Run Unit Tests
  - [x] XUnit
  - [x] Fluent Assertions
  - [x] Inline Data
- [x] Testing Objects, IEnumberable & Dates
  - [x] Intro
  - [x] System Under Test
  - [x] Date Time
  - [x] Test Date
  - [x] Testing an Object
  - [x] IEnumerable
  - [x] Ping Objects
  - [x] Type Check
  - [x] Debugging
- [x] Mocking Explained Simply [FakeItEasy]
- [x] MVC Controllers
- [x] MVC Entity Framework
  - [x] Intro
  - [x] Building the Repository
  - [x] Database Context
  - [x] Code
  - [x] Demo
- [x] Web API Controllers
  - [x] Intro
  - [x] Project Setup
  - [x] Mocking Framework
  - [x] Fluent Assertions
  - [x] Testing Controllers
  - [x] Why Mock?
  - [x] Adding Repository
  - [x] Fake Controller
  - [x] Return
  - [x] Fake
  - [x] Mock
  - [x] New Controller
  - [x] Inline Theory
  - [x] Outro
- [x] Web API Entity Framework
  - [x] Intro
  - [x] Database Context
  - [x] In Memory
  - [x] Testing
