### ISSUE TITLE
.Net 5 API

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#117]
.Net 5 REST API Tutorial

Link: https://www.youtube.com/playlist?list=PLeD0-5Hw0ZJ_GlY21kfzfQD-N17i8pdTS

### Milestones

- [ ] 1. Getting Started
- [ ] 2. Entity, Repository, Controller (GET)
- [ ] 3. Dependency Injection, DTOs
- [ ] 4. POST, PUT, DELETE
- [ ] 5. Persisting entities with MongoDB
- [ ] 6. Tasks, Async and Await
- [ ] 7. Secrets and Health Checks
- [ ] 8. Docker
- [ ] 9. Kubernetes
- [ ] 10. Unit Testing and TDD
