### ISSUE TITLE
.Net 7 Razor Pages Full Course

### ISSUE THREAD

**Issue by syafiqhadzir** [SyafiqHadzir/Personal-Milestone#118]
ASP.Net Core Razor Pages with .Net 7 for beginners. (Full Course)

Link: <https://www.youtube.com/watch?v=QmoCAjYDYSI>

### Milestones

- [x] Welcome to course
- [x] Prerequisites
- [x] Development tools
- [x] Create a new razor pages project
- [x] Our first run
- [x] Explore the solution explorer
- [x] launchSetting.json
- [x] appSettings.json
- [x] wwwroot folder
- [x] Program.cs
- [x] Routing
- [x] Page,PageModel and page handlers OnGet(),OnPost()
- [x] Retrieve data from appSetting.json and Depepndency Injection
- [x] Removing all the boilerplate files
- [x] _ViewImports.cshtml
- [x] Resuming the boilerplate cleanup
- [x] Create new Index page
- [x] Adding bootstrap design to index
- [x] Using bootswatch themes
- [x] Link navigations with anchor tag helpers
- [x] Need of layout
- [x] Create a layout page
- [x] _ViewStart.cshtml
- [x] PartialView
- [ ] Designing basic index page
- [ ] Category creation page
- [ ] Person model and validation
- [ ] Database Connectivity with Entity framework
- [ ] Create a person
- [ ] Display person record
- [ ] Edit person
- [ ] Delete person
- [ ] Add new table
- [ ] Adding new field to person
- [ ] Create a file upload class
- [ ] Adding a profile picture upload feature in person
- [ ] Scaffolding
- [ ] End of course
