### ISSUE TITLE
PHP Unit Testing

### ISSUE THREAD

**Issue by syafiqhadzir** [SyafiqHadzir/Personal-Milestone#119]
PHP Unit Testing

Playlist: https://www.youtube.com/playlist?list=PLe30vg_FG4OTsFRc1eWppZfYwZdMlLuhE

### Milestones

- [ ] Why we need Testing of Code
- [ ] What is unit Testing
- [ ] Write your First Ever Test
- [ ] Getting Started with PHPUnit
- [ ] Start Laravel Testing
- [ ] What is Database Transaction in Laravel Testing
- [ ] Why use Database Migration
- [ ] Test with Model Factory
- [ ] Test with Logged in User and Exception Testing
- [ ] Visit to see all Beverages
- [ ] Visit a single Beverage
- [ ] Authenticated User Buy a Beverage
