### ISSUE TITLE
NodeJS Web Scraping

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#12]
Tutorial: Learn Web Scraping with NodeJs in 2021 (Udemy)

Link: https://www.udemy.com/course/nodejs-web-scraping/

### Milestones

- [ ] **Introduction**
  - [ ] Introduction
  - [ ] Tools & Project Setup
  - [ ] Writing a Simple IMDB Scraper
- [ ] **More Info & Concepts**
  - [ ] Why & When to Choose Scraping
  - [ ] The Biggest "Problem" with Scraping
  - [ ] Running with Terminal / CMD & Basics on VSCode Debugger
  - [ ] The Request Library / Method
  - [ ] The Browser Automation Method
- [ ] **IMDB Simple Scraper (Request Method)**
  - [ ] 1. How to Spoof / Add Custom Request Headers
  - [ ] 2. Deal with GZIP Compression Enabled Websites
  - [ ] 3. Selectors & More Parsing
  - [ ] 4. Multiple Movies & Saving JSON to File
  - [ ] 5. Exporting Data to CSV
  - [ ] 6. Easiest Method of Getting The Proper Selectors
  - [ ] 7. Dowloading Images Locally
  - [ ] 8. Promisifying Callback Based Functions
- [ ] **Request Method**
  - [ ] Using a Proxy Server
  - [ ] Status Codes & Error Handling
  - [ ] Manual Login with CSRF Protection & Cookie Parsing
- [ ] **Instagram User Simple Scraper (Request Method)**
  - [ ] 1. Introduction and Inspecting The Structures
  - [ ] 2. Building The Scraper
  - [ ] 3. Parsing Latest Posts of an IG User
- [ ] **The Puppeteer Method**
  - [ ] 1. Installation, Introduction and Testing
  - [ ] 2. Writing a Simple Automated Task
  - [ ] 3. Generating PDF's, Emulating Phone Views, Getting Title & URL of Pages
  - [ ] 4. Using Puppeteer To Login on Instagram
  - [ ] 5. Making Websites Load Much Faster with a Simple Trick
  - [ ] 6. HTTP Basic Authentication
  - [ ] 7. Ignoring HTTPS / SSL Errors & Changing the ViewPort
  - [ ] 8. Learning How To Use Proxies
  - [ ] 9. Exposing and Working with Custom Functions in Puppeteer
- [ ] **Twitter Scraper with Puppeteer**
  - [ ] 1. How To Login on Twitter
  - [ ] 2. Refactoring Code and Improving It
  - [ ] 3. How To Post Tweets with Puppeteer
  - [ ] 4. Scraping Twitter Users Details
  - [ ] 5. Scraping More Users Details
  - [ ] 6. Scraping User Tweets
  - [ ] 7. Scraping More Tweet Details (Likes, Replies ... etc.)
  - [ ] 8. Handling The Infinite Loader of The Tweets
- [ ] **Amazon Scraper with Puppeteer**
  - [ ] 1. Creating The Module Structure
  - [ ] 2. Parsing Product Details
  - [ ] 3. More Details and Tricks on The Product Details Page of Amazon
- [ ] **The NightmareJs Method**
  - [ ] 1. Installation, Introduction and Testing
  - [ ] 2. Talking and Testing More About NightmareJs
  - [ ] 3. Scraping Ycombinator News with Vanilla Javascript
  - [ ] 4. Scraping Ycombinator News - More Details
  - [ ] 5. Scraping Ycombinator News - Modulate & Pagination
  - [ ] 6. Handling Downloads
  - [ ] 7. Injecting Custom Javascript
- [ ] **The End**
  - [ ] Congratulations!
