### ISSUE TITLE
Wireshark Complete Course

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#13]
The Complete Wireshark Course Beginner To Advanced (Complete Course)

Link: https://www.youtube.com/watch?v=zOYohNOnWp4

### Milestones

- [ ] Introduction to Wireshark
- [ ] Basic Networking Terms & Concepts
- [ ] OSI Model
- [ ] Wireshark Installation & Setup
- [ ] Wireshark Interface
- [ ] Wireshark Interface (Pt. 2)
- [ ] IP & Port Filters
- [ ] Protocol Filters
- [ ] HTTP Packet Analysis
- [ ] Extracting Credentials
- [ ] Wireshark & Linux Firewall Interaction
- [ ] Demonstration Detecting Unauthorized Traffic
- [ ] Introduction to Wireshark CLI
- [ ] First Usage of Wireshark CLI
- [ ] T Shark File Output
- [ ] T Shark Timer Limits
- [ ] T Shark Splitting Output Files
- [ ] Display & Capture Filters Differences
- [ ] Field Separation in T Shark
- [ ] Network card modes
- [ ] How To Enable Monitor Mode
- [ ] How To Enable Monitor Mode (Pt. 2)
- [ ] Capture Remote Traffic
- [ ] Decrypting Wireless Traffic
- [ ] T Shark Output Formatting (CSV)
- [ ] T Shark Output Formatting (Packet)
- [ ] Wireshark and Nmap
- [ ] Wireshark and Nmap (Pt. 2)
- [ ] SSH Tunneling to Wireshark
- [ ] SSH Tunneling to Wireshark (Pt. 2)
- [ ] SSH Tunneling to Wireshark (Pt. 3)
- [ ] SSH Tunneling to Wireshark (Pt. 4)
