### ISSUE TITLE
Cybersecurity Complete Course

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#14]
Tutorial: Reverse Engineering, Debugging and Malware Analysis - 2021 (Udemy)

Link: https://www.udemy.com/course/reverse-engineering-debugging-and-malware-analysis-2021/

### Milestones

- [ ] **Reverse Engineering Fundamentals**
  - [ ] Reverse Engineering Fundamentals
  - [ ] Reverse Engineering Tools
  - [ ] Analysis Types and Reporting
- [ ] **Operating System Components**
  - [ ] Filesystem
  - [ ] Non-Volatile Memory
  - [ ] The Windows Registry
  - [ ] Volatile Memory
  - [ ] Operating System Components
- [ ] **Malware Behavior**
  - [ ] Analysis Tools
  - [ ] Malware Identification
  - [ ] Persistence
  - [ ] Malware Persistence
- [ ] **Malware and Memory Analysis**
  - [ ] Volatility Cridex
  - [ ] Volatility R2D2
  - [ ] Cridex Malware Analysis
- [ ] **Debugging**
  - [ ] Low Level (Assembly) Debugging With Immunity Debugger
- [ ] **Software Exploitation**
  - [ ] Software Exploitation Intro and Stack Frames in Memory
  - [ ] Low-Level View and Managing Stacks
  - [ ] Stack Reliability and GCC Example
  - [ ] Methods Exploitation
  - [ ] Stack Guards Bypass
  - [ ] Stack Guards Bypass - Part 2
  - [ ] Evil Server
  - [ ] Test
