### ISSUE TITLE
C# Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#15]
C# - Programming Language (Tutorial)

Playlist: https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpNIBTYHNDrhfE9C-imUXCmk

Repository: https://gitlab.com/SyafiqHadzir/c-sharp-tutorial/

### Milestones

- [ ] Introduction
- [ ] Installation & Setup
- [ ] Drawing a Shape
- [ ] Variables
- [ ] Data Types
- [ ] Working With Strings
- [ ] Working With Numbers
- [ ] Getting User Input
- [ ] Building a Calculator
- [ ] Building a Mad Lib
- [ ] Arrays (Pt. 1)
- [ ] Methods
- [ ] Return Statement
- [ ] If Statement (Pt. 1)
- [ ] If Statement (Pt. 2)
- [ ] Building a Better Calculator
- [ ] Switch Statements
- [ ] While Loops
- [ ] Building a Guessing Game
- [ ] For Loops
- [ ] Building an Exponent Method
- [ ] Arrays (Pt. 2)
- [ ] Comments
- [ ] Exception Handling
- [ ] Classes & Objects
- [ ] Constructors
- [ ] Object Methods
- [ ] Getters & Setters
- [ ] Static Class Attributes
- [ ] Static Methods & Classes
- [ ] Inheritance
