### ISSUE TITLE
Introduction to Algorithms

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#18]
Cormen, T. H. et al. _Introduction to Algorithms._ 2009.

Reading list: https://blog.syafiqhadzir.dev/Readings

### Milestones

- [ ] **Foundations**
  - [ ] The Role of Algorithms in Computing
  - [ ] Getting Started
  - [ ] Growth of Functions
  - [ ] Divide-and-Conquer
  - [ ] Probabilistic Analysis and Randomized Algorithms
- [ ] **Sorting and Order Statistics**
  - [ ] Heapsort
  - [ ] Quicksort
  - [ ] Sorting in Linear Time
  - [ ] Medians and Order Statistics
- [ ] **Data Structures**
  - [ ] Elementary Data Structures
  - [ ] Hash Tables
  - [ ] Binary Search Trees
  - [ ] Red-Black Trees
  - [ ] Augmenting Data Structures
- [ ] **Advanced Design and Analysis Techniques**
  - [ ] Dynamic Programming
  - [ ] Greedy Algorithms
  - [ ] Amortized Analysis
- [ ] **Advanced Data Structures**
  - [ ] B-Trees
  - [ ] Fibonacci Heaps
  - [ ] van Emde Boas Trees
  - [ ] Data Structures for Disjoint Sets
- [ ] **Graph Algorithms**
  - [ ] Elementary Graph Algorithms
  - [ ] Minimum Spanning Trees
  - [ ] Single-Source Shortest Paths
  - [ ] All-Pairs Shortest Paths
  - [ ] Maximum Flow
- [ ] **Selected Topics**
  - [ ] Multithread Algorithms
  - [ ] Matrix Operations
  - [ ] Linear Programming
  - [ ] Polynomials and the FFT
  - [ ] Number-Theoretic Algorithms
  - [ ] String Matching
  - [ ] Computational Geometry
  - [ ] NP-Completeness
  - [ ] Approximation Algorithms
- [ ] **Mathematical Background**
  - [ ] Summations
  - [ ] Sets, Etc.
  - [ ] Counting and Probability
  - [ ] Matrices
