### ISSUE TITLE
JavaScript For Testers

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#2]
JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour

Link: https://www.youtube.com/watch?v=W6NZfCO5SIk

Repository: https://gitlab.com/SyafiqHadzir/javascript-tutorial/-/tree/main/tutorials/javascript-tutorial-beginners

### Milestones

- [x] What is JavaScript
- [x] Setting Up the Development Environment
- [x] JavaScript in Browsers
- [x] Separation of Concerns
- [x] JavaScript in Node
- [x] Variables
- [x] Constants
- [x] Primitive Types
- [x] Dynamic Typing
- [x] Objects
- [x] Arrays
- [x] Functions
- [x] Types of Functions
