### ISSUE TITLE
Understanding TCP/IP: A Clear and Comprehensive Guide to TCP/IP Protocols

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#20]
Dostálek, L. & Kabelová, A. _Understanding TCP/IP: A Clear and Comprehensive Guide to TCP/IP Protocols_. 2006.

Reading list: https://blog.syafiqhadzir.dev/Readings

### Milestones

- [ ] **Introduction to Network Protocols**
  - [ ] ISO OSI
  - [ ] TCP/IP
  - [ ] Methods of Information Transmission
  - [ ] Virtual Circuit
- [ ] **Network Monitoring Tools**
  - [ ] Packet Drivers
  - [ ] MS Network Monitor
  - [ ] Ethereal
  - [ ] Homework
- [ ] **Physical Layer**
  - [ ] Serial Line
  - [ ] Modems
  - [ ] Digital Circuits
  - [ ] LAN
- [ ] **Link Layer**
  - [ ] Serial Line Internet Protocol
  - [ ] Compressed SLIP
  - [ ] High-Level Data Link Control Protocol
  - [ ] Point-to-Point Protocol
  - [ ] Frame Relay
  - [ ] Local Area Networks
  - [ ] Wireless Local Area Network
  - [ ] Fixed Wireless Access
- [ ] **Internet Protocol**
  - [ ] IP Datagram
  - [ ] Internet Control Message Protocol
  - [ ] Fragmentation
  - [ ] Optional Entries in the IP Header
  - [ ] ARP and RARP Protocols
  - [ ] Internet Group Management Protocol
  - [ ] Multicast and Link Protocol
- [ ] **IP Address**
  - [ ] Network: First Period of History
  - [ ] Network: Second Period of History
  - [ ] IP Addresses in the Intranet and Special-Use IP Addresses
  - [ ] Unnumbered Interface
  - [ ] Address Plan
  - [ ] Over 254 Interfaces in a LAN
- [ ] **Routing**
  - [ ] Forwarding and Screening
  - [ ] Routing
  - [ ] Handling Routing Tables
  - [ ] Routing Protocols
  - [ ] Neutral Exchange Point
- [ ] **IP Version 6**
  - [ ] Next Headers of IP Version 6 Datagram
  - [ ] ICMP Version 6 Protocol
  - [ ] IP Addresses
  - [ ] Windows 2003
- [ ] **Transmission Control Protocol**
  - [ ] TCP Segments
  - [ ] TCP Header Options
  - [ ] Establishing and Terminating a Connection with TCP
  - [ ] Determining the Connection State
  - [ ] Response Delay Techhniques
  - [ ] Window Technique
  - [ ] Network Congestion
- [ ] **User Datagram Protocol**
  - [ ] Fragmentation
  - [ ] Broadcasts and Multicasts
- [ ] **Domain Name System**
  - [ ] Domains and Subdomains
  - [ ] Name Syntax
  - [ ] Reverse Domains
  - [ ] Resource Records
  - [ ] DNS Protocol
  - [ ] DNS Query
- [ ] **Telnet**
  - [ ] The NVT Protocol
  - [ ] Telnet Protocol Commands
  - [ ] Example of Windows NT Client Communication
  - [ ] Example of UNIX Client Communication
- [ ] **File Transfer Protocol**
  - [ ] Architecture
  - [ ] Active Mode of FTP Protocol Communication
  - [ ] Passive Mode of FTP Protocol Communication
  - [ ] FTP Commands
  - [ ] Proxy
  - [ ] Return Codes
  - [ ] Abnormal Terminations of Data Transfer
  - [ ] Anonymous FTP
- [ ] **Hypertext Transfer Protocol**
  - [ ] Client-Server
  - [ ] Proxy
  - [ ] Gateway
  - [ ] Tunnel
  - [ ] More Intermediate Nodes
  - [ ] Uniform Resource Identifier
  - [ ] Relative URI
  - [ ] The HTTP Request
  - [ ] The HTTP Response
  - [ ] Other Header Fields
  - [ ] Cookie
- [ ] **Email**
  - [ ] Email Architecture
  - [ ] Mail Message Format
  - [ ] MIME
  - [ ] SMTP
  - [ ] ESMTP
  - [ ] POP3
  - [ ] IMAP4
  - [ ] Mailing Lists
- [ ] **Forums**
  - [ ] Message Format
  - [ ] NNTP Protocol
- [ ] **Lightweight Directory Access Protocol**
  - [ ] Protocol Principle
  - [ ] Data Model of LDAP Directory
  - [ ] LDAP Protocol Data Units
  - [ ] Server Programs
  - [ ] Client Programs
  - [ ] Lightweight Directory Interchange Format

**Comment by SyafiqHadzir** [comment]
As per 11:41, 7 March 2022,

[Introduction_ISO-OSI.pdf](https://github.com/SyafiqHadzir/Personal-Milestone/files/8194590/Introduction_ISO-OSI.pdf)
