### ISSUE TITLE
CSS Basic Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#24]
CSS - Style Your Website (Tutorial)

Playlist: https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpNO7ScZFr-WTmtcBY3AN1M7

Repository: https://gitlab.com/SyafiqHadzir/css-tutorial/-/tree/main/tutorials/css-style-your-website

### Milestones

- [x] Introduction
- [x] Basic Inline Styling
- [x] Colors
- [x] Margins & Padding
- [x] Display & Floats
- [x] Position - Static, Relative, Absolute, Fixed
- [x] Shadows, Opacity & Border Radius
- [x] Text & Fonts
- [x] Style Tags
- [x] External Style Sheets
- [x] IDs & Classes
- [x] CSS Selectors
- [x] Flexbox
- [x] Animations
- [x] Imports
- [x] Browser Support
- [x] CSS Frameworks
