### ISSUE TITLE
Tailwind CSS Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#25]
Tailwind CSS: From Zero to Production

Playlist: <https://www.youtube.com/watch?v=elgqxmdVms8&list=PL5f_mz_zU5eXWYDXHUDOLBE0scnuJofO0>

### Milestones

- [x] Course Intro
- [x] Setting Up Tailwind CSS
- [x] The Utility-First Workflow
- [x] Responsive Design
- [x] Hover, Focus and Other States
- [x] Composing Utilities with @apply
- [x] Extracting Reusable Components
- [x] Customizing Your Design System
- [x] Optimizing for Production
