### ISSUE TITLE
Sass Tutorial for Beginners

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#26]
Sass Tutorial for Beginners - CSS With Superpowers

Playlist: https://www.youtube.com/watch?v=_a5j7KoflTs

Repository: https://gitlab.com/SyafiqHadzir/css-tutorial/-/tree/main/tutorials/sass-tutorial-beginner

### Milestones

- [x] Intro
- [x] What Is Sass?
- [x] Requirements
- [x] Install/Setup Live Sass Compiler VS Code Extension
- [x] Folder Structure / Sass Syntax
- [x] Variables
- [x] Maps
- [x] Nesting
- [x] Partials
- [x] Functions
- [x] Mixin Example 1
- [x] Mixin Example 2
- [x] Mixin Example 3
- [x] Extend
- [x] Math Operations
- [x] How to Learn More (Documentation)
- [x] Real-World Example from Scratch (Portfolio Site)
- [x] index.html
- [x] Font Awesome Setup
- [x] main.scss / \_config.scss
- [x] \_home.scss
- [x] Transition Ease Mixin
- [x] Text Color Function
- [x] \_menu.scss
- [x] main.js
- [x] Menu cont.
- [x] about.html
- [x] \_about.scss
- [x] projects.html
- [x] \_projects.scss
- [x] contact.html
- [x] \_contact.scss
- [x] \_responsive.scss
- [x] Deploy on GitHub Pages
