### ISSUE TITLE
Dart Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#3]
Dart Programming in 4 hours | Full beginners tutorial

Link: https://www.youtube.com/watch?v=5xlVP04905w

Repository: https://gitlab.com/SyafiqHadzir/kotlin-tutorial/-/tree/main/tutorials/dart-tutorial-beginners

### Milestones

- [x] Introduction
- [x] Environment overview
- [x] What is programming?
- [x] Print Statements
- [x] Program execution flow
- [x] Variables
- [x] Data Types
- [x] String Basics
- [x] Numbers - ints & doubles
- [x] Booleans
- [x] Getting user input
- [x] Building a basic calculator
- [x] Building a madibs game
- [x] Lists
- [x] Functions
- [x] Parameters & Arguments
- [x] Return Statements
- [x] Building a prompt function
- [x] If Statements
- [x] And & Or operators
- [x] Else If
- [x] Building a smarter calculator
- [x] Switch Statements
- [x] While Loops
- [x] Building a guessing game
- [x] For Loops
- [x] Comments
- [x] Classes & Objects
- [x] Constructors
- [x] Class Methods
- [x] Final Project - Building a math quiz
- [x] Outro & next steps
