### ISSUE TITLE
LaTex Tutorial for Beginners

### ISSUE THREAD

**Issue by syafiqhadzir** [SyafiqHadzir/Personal-Milestone#31]
# LaTex Tutorial for Beginners

Learn LaTex - Full Course for Beginners (Tutorial)

Repository: <https://gitlab.com/SyafiqHadzir/technical-theories/-/tree/main/tutorials/latex-tutorial-beginners>

Link: <https://www.youtube.com/watch?v=rfscVS0vtbw>

### Milestones

- [x] Introduction
- [x] Basic Text Manipulation
- [x] Basic Math Manipulation
- [x] Tables and Arrays
- [x] Calculus Notation
- [ ] Miscellaneous Notation
- [ ] Working with Numbers
- [ ] Basic Customization
- [ ] LaTeX Environments
- [ ] TikZ (Part 1)
- [ ] TikZ (Part 2)
- [ ] TikZ (Part 3)
- [ ] Beamer
