### ISSUE TITLE
TypeScript Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#35]
TypeScript for React (Learn TypeScript, 2020)

Link: <https://www.youtube.com/watch?v=NjN00cM18Z4>

### Milestones

- [x]  What is TypeScript?
- [x]  Your First TypeScript Program
- [x]  Declaring Variables
- [x]  Types
- [x]  Type Assertions
- [x]  Arrow Functions
- [x]  Interfaces
- [x]  Classes
- [x]  Objects
- [x]  Constructors
- [x]  Access Modifiers
- [x]  Access Modifiers in Constructor Parameters
- [x]  Properties
- [x]  Modules
