### ISSUE TITLE
Protractor Beginner Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#36]
# Protractor Beginner Tutorial

Protractor is an end-to-end test framework for Angular and AngularJS applications.

Link: <https://www.youtube.com/playlist?list=PLhW3qG5bs-L_dgIr3hiOlnNIO8NGlXQnP>

### Milestones
- [ ] What is Protractor
- [ ] Why We Need Protractor?
- [ ] How Protractor Works?
- [ ] How to setup Protractor on Windows
- [ ] How to setup Protractor on Mac
- [ ] Creating Protractor Framework on Visual Studio Code from Scratch
- [ ] How to create First Test Case in Protractor
- [ ] Protractor How to find Element Locators
- [ ] POM in Protractor
- [ ] How to take Screenshots in Protractor
- [ ] How to create Allure HTML Reports in Protractor
- [ ] How to create HTML Reports with Screenshots on Failure
- [ ] How to upload Project on Git (Version Control)
- [ ] How to run Protractor Tests from Jenkins
- [ ] Jenkins Integration
- [ ] How to generate Allure Reports in Jenkins
