### ISSUE TITLE
Flask Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#38]
# Flask Tutorial

Learn how to build a full-feature Flask application for scratch.

Playlist: <https://www.youtube.com/playlist?list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH>

### Milestones

- [ ] Getting Started
- [ ] Templates
- [ ] Forms and User Input
- [ ] Database with Flask-SQLAlchemy
- [ ] Package Structure
- [ ] User Authentication
- [ ] User Account and Profile Picture
- [ ] Create, Update and Delete Posts
- [ ] Pagination
- [ ] Email & Password Reset
- [ ] Blueprints and Configuration
- [ ] Custom Error Pages
- [ ] Deploy to a Linux Server
- [ ] How to use a Custom Domain Name for Our Application
- [ ] How to enable HTTPS with a Free SSL/TLS Certificate using Let's Encrypt
