### ISSUE TITLE
Python Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#4]
Learn Python - Full Course for Beginners (Tutorial)

Link: https://www.youtube.com/watch?v=rfscVS0vtbw

Repository: https://gitlab.com/SyafiqHadzir/python-tutorial

### Milestones

- [x] Introduction
- [x] Installing Python & PyCharm
- [x] Setup & Hello World
- [x] Drawing a Shape
- [x] Variables & Data Types
- [x] Working with Strings
- [x] Working with Numbers
- [x] Getting Input from Users
- [x] Building a Basic Calculator
- [x] Mad Libs Game
- [x] Lists
- [x] List Functions
- [x] Tuples
- [x] Functions
- [x] Return Statement
- [x] If Statements
- [x] If Statements & Comparisons
- [x] Building a Better Calculator
- [x] Dictionaries
- [x] While Loop
- [x] Building a Guessing Game
- [x] For Loops
- [x] Exponent Function
- [x] 2D Lists & Nested Loops
- [x] Building a Translator
- [x] Comments
- [x] Try / Except
- [x] Reading Files
- [x] Writing to Files
- [x] Modules & Pip
- [x] Classes & Objects
- [x] Building a Multiple Choice Quiz
- [x] Object Functions
- [x] Inheritance
- [x] Python Interpreter
