### ISSUE TITLE
Learning JavaScript Design Patterns

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#45]
Osmani, A. _Learning JavaScript Design Patterns._ 2012.

Reading list: https://blog.syafiqhadzir.dev/Readings

### Milestones

* [ ] **Introduction**
* [ ] **What Is a Pattern?**
  * [ ] We Already Use Patterns Every Day
* [ ] **"Pattern"-ity Testing, Proto-Patterns, and the Rule of Three**
* [ ] **The Structure of a Design Pattern**
* [ ] **Writing Design Patterns**
* [ ] **Anti-Patterns**
* [ ] **Categories of Design Patterns**
  * [ ] Creational Design Patterns
  * [ ] Structural Design Patterns
  * [ ] Behavioral Design Patterns
* [ ] **Design Pattern Categorization**
  * [ ] A Brief Note on Classes
* [ ] **JavaScript Design Patterns**
  * [ ] The Constructor Pattern
    * [ ] Object Creation
    * [ ] Basic Constructors
    * [ ] Constructors with Prototypes
  * [ ] The Module Pattern
    * [ ] Object Literals
    * [ ] The Module Pattern
    * [ ] Module Pattern Variations
  * [ ] The Revealing Module Pattern
    * [ ] Advantages
    * [ ] Disadvantages
  * [ ] The Singleton Pattern
  * [ ] The Observer Pattern
    * [ ] Differences Between the Observer and Publish/Subscribe Pattern
    * [ ] Advantages
    * [ ] Disadvantages
    * [ ] Publish/Subscribe Implementations
