### ISSUE TITLE
Gatsby Tutorial for Beginners

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#46]
# Gatsby Tutorial for Beginners

Gatsby - Static Site Generator Tutorial

Link: <https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpMXuwazIt4mWtTuqOHdjRlk>

### Milestones

* [x] Introduction
* [x] Mac & Windows Installation
* [x] Creating a New Site
* [x] Adding Content
* [x] Linking Pages
* [x] Interactive Pages
* [x] Building Your Site
* [x] Components
* [x] Plugins
* [x] Layouts
* [x] Site Data
* [x] File Data
* [x] Working with Markdown
