### ISSUE TITLE
Coffee Script Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#50]
Coffee script tutorials

Playlist: <https://www.youtube.com/playlist?list=PL399DF0B74063889F>

### Milestones

- [x] How to install Coffee Script
- [x] Writing and Compiling Your First Coffee Script
- [x] How to write Functions in Coffee Script
- [x] Operators and Aliases
- [x] How to use Conditional Statements in Coffee Script
- [x] The Existential Operator in Coffee Script
- [x] Arrays and Objects in Coffee Script
- [x] Using String Interpolation Block Strings and Block Comments
- [x] For Loops and List Comprehension
- [x] Splats
- [x] Array Slicing and Splicing with Ranges
- [x] Switch Statements
