### ISSUE TITLE
JavaScript Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#6]
JavaScript - Programming Language (Tutorial)

Playlist: https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpPQbcrA-SzALJeFm23tPrAI

Repository: https://gitlab.com/SyafiqHadzir/javascript-tutorial/-/tree/main/tutorials/javascript-language-tutorial

### Milestones

- [x] Introduction
- [x] Choosing a Text Editor
- [x] Setup & Hello World
- [x] Using External Files
- [x] Writing HTML in JavaScript
- [x] Variables & Data Types
- [x] Working With Strings
- [x] Math & Numbers
- [x] Getting User Input
- [x] A Basic Calculator
- [x] Arrays
- [x] Functions
- [x] Accessing HTML Elements
- [x] Event Listeners
- [x] Building a Messaging App
- [x] If Statements
- [x] If Statements w/ comparisons
- [x] Switch Statements
- [x] Objects
- [x] Real World Objects
- [x] While Loops
- [x] Building a Password Checker
- [x] For Loops
- [x] Building a Multiple Choice Quiz
- [x] Nested Loops & 2D Arrays
- [x] For Each Loops
- [x] Timing
- [x] Web Storage
