### ISSUE TITLE
PHP 8 Tutorial

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#7]
Learn PHP The Right Way: Full PHP Tutorial For Beginner & Advanced

Playlist link: https://www.youtube.com/watch?v=sVbEyFZKgqk&list=PLr3d3QYzkw2xabQRUpcZ_IBk9W50M9pe-

### Milestones

- [ ] Introduction
- [ ] Installation
- [ ] Basic Syntax
- [ ] Constants & Variables
- [ ] Data Types
- [ ] Boolean Data Type
- [ ] Integer Data Type
- [ ] Float Data Type
- [ ] String Data Type
- [ ] Null Data Type
- [ ] Array Data Type
- [ ] Expressions
- [ ] Operators (Part 1)
- [ ] Operators (Part 2)
- [ ] Operator Precedence & Associativity
- [ ] Control Structures
- [ ] Loops
- [ ] Switch Statement
- [ ] Match Expression
- [ ] Return, Declare & Tickable Statements
- [ ] How To Include Files
- [ ] How To Create Functions
- [ ] Fuction Parameters
- [ ] Variable Scopes
- [ ] Variable, Anonymous, Callable, Closure & Arrow Functions
- [ ] Dates & Time Zones
- [ ] Arrays
- [ ] Configuration File
- [ ] Error Handling & Error Handlers
- [ ] Basic Apache Webserver Configuration & Virtual Hosts
- [ ] Working With File System
- [ ] Mini Exercise Project Overview
- [ ] Building Small Part Of The App With Procedural
- [ ] OOP Tutorial Section 2
- [ ] Docker Tutorial
- [ ] Classes & Objects
- [ ] Constructor Property Promotion
- [ ] Namespace Tutorial
- [ ] Coding Standards, Autoloading (PSR-4) & Composer
- [ ] Object Oriented
- [ ] Static Properties & Methods
- [ ] Encapsulation & Abstraction
- [ ] Inheritance Explained
- [ ] Abstract Classes & Methods
- [ ] Interfaces & Polymorphism
- [ ] Magic Methods
- [ ] Late Static Binding
- [ ] Traits
- [ ] Anonymous Classes
- [ ] Variable Storage & Object Comparison
- [ ] DocBlock
- [ ] Object Cloning & Clone Magic Method
- [ ] Serialize Objects & Serialize Magic Methods
- [ ] OOP Error Handling
- [ ] DateTime Object
- [ ] Iterators & Iterable Types
- [ ] Superglobals
- [ ] Get & Post Superglobals
- [ ] Sessions & Cookies
- [ ] File Uploads
- [ ] MVC Pattern
- [ ] HTTP Headers
- [ ] Introduction to MySQL
- [ ] PDO (Part 1)
- [ ] PDO (Part 2)
- [ ] PDO (Part 3)
- [ ] Exercise
- [ ] Introduction to Testing
- [ ] PHP Unit Testing (Part 1)
- [ ] PHP Unit Testing (Part 2)
- [ ] Dependency Injection & DI Containers
- [ ] Dependency Injection Container
