### ISSUE TITLE
Cypress Crash Course

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#8]
Learn Full E2E Testing Using Cypress | 2020 Update

Link: https://www.youtube.com/watch?v=OIAzwr-_jhY

Repository: [https://gitlab.com/SyafiqHadzir/qa-notes](https://gitlab.com/SyafiqHadzir/qa-notes/-/tree/main/cypress-tutorials/cypress-crash-course)

### Milestones

- [x] Intro
- [x] How Cypress Work
- [x] Course Outcome & Pre-reqs
- [x] Installing Node
- [x] Installing Cypress
- [x] Exploring Cypress Runner
- [x] Hello World
- [x] Headless Hello World
- [x] Folder Structure
- [x] cy.contains
- [x] cy.get
- [x] cy.should
- [x] cy.viewport
- [x] Verifying Login Page Looks Good
- [x] Verifying Page URLs
- [x] cy.login
- [x] Typing With Cypress
- [x] Logging In With Cypress
- [x] beforeEach
- [x] Set localStorage
- [x] Real Project: Codedamn Playground Testing
- [x] Checking For Element Existence
- [x] Command Level Timeout
- [x] Testing New File
- [x] Rename File Test
- [x] Outro
