### ISSUE TITLE
Unit Testing with Mocha and Chai

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#9]
Unit testing with Mocha and Chai

Link (1): https://www.youtube.com/watch?v=k4GFqgBR2qc

Link (2): https://www.youtube.com/watch?v=gD4Sg3OuMiA

Repository: https://gitlab.com/SyafiqHadzir/qa-notes/-/tree/main/mocha-tutorials/unit-testing-mocha-chai

#### Part 1

- [x] Introduction
- [x] Installing dependencies
- [x] Setting Up
- [x] Writing First Unit Test
- [x] Chai
- [x] Useful Unit Tests
- [x] Exercise
- [x] Using nyc

#### Part 2

- [x] Introduction
- [x] Installing Dependencies
- [x] Setting Up Test File
- [x] Writing a Unit Test
- [x] The Done Callback
- [x] Unit Tests Not Integration Tests
- [x] Using Sinon and Stubs
- [x] Testing The Get User Repository Method
- [x] BeforeEach and AfterEach Functions and Sinon Sandbox
- [x] Testing for Promise Rejections
- [x] Wrap-Up
