### ISSUE TITLE
C# Unit Testing Tutorial for Beginners

### ISSUE THREAD

**Issue by SyafiqHadzir** [SyafiqHadzir/Personal-Milestone#95]
# C# Unit Testing Tutorial for Beginners

Unit Testing C# Code - Tutorial for Beginners.

Link: <https://www.youtube.com/watch?v=HYrXogLj7vg>

### Milestones

- [x] What is Automated Testing
- [x] Benefits of Automated Testing
- [x] Types of Tests
- [x] Test Pyramid
- [x] The Tooling
- [x] Source Code
- [x] Writing Your First Unit Test
- [x] Testing All the Execution Paths
- [x] Refactoring With Confidence
- [x] Using NUnit in Visual Studio
- [x] What is Test-Driven Development
- [x] Course Structure
- [x] Summary
